name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy to GitHub Pages
      run: |
        npm install
        npm run build
        npm run test
        echo 'olumide.co' > public/CNAME
        git config --global user.email 'olumytee.ojo@gmail.com'
        git config --global user.name 'olumide ojo'
        cd public
        ls
        cd ..
        git subtree push --prefix public/ origin master
        
      
